# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Tie-Cache-0.17

DESCRIPTION="In memory size limited LRU cache"
HOMEPAGE="http://search.cpan.org/search?query=Tie-Cache&mode=dist"
SRC_URI="mirror://cpan/authors/id/C/CH/CHAMAS/Tie-Cache-0.17.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~x86"

