# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/NetAddr-IP-4.007

DESCRIPTION="Manipulation and operations on IP addresses"
HOMEPAGE="http://search.cpan.org/search?query=NetAddr-IP&mode=dist"
SRC_URI="mirror://cpan/authors/id/L/LU/LUISMUNOZ/NetAddr-IP-4.007.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~x86"

DEPEND="dev-lang/perl"
