# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Krb5-1.6

DESCRIPTION="Interface to Kerberos 5 API"
HOMEPAGE="http://search.cpan.org/search?query=Krb5&mode=dist"
SRC_URI="mirror://cpan/authors/id/J/JH/JHORWITZ/Krb5-1.6.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~x86"

